### ISSUE TITLE
Multiple chat rooms?

### ISSUE THREAD

**Issue by eduardofcgo** [JAVEO/clustered-chat#3]
I'm having an hard time implementing multiple chat rooms. We should have an actor for each room, but where will it be created? Should it be a child of the UserSocket? Could I create different pubsub channel for every room?
Thanks a lot for the help

**Comment by sergiuszkierat** [comment]
@eduardofcbg, I could imagine that the multiple rooms is a next step for this activator. There are many aspects how to do it. To simplify, we can assume that we can create some static rooms so as to choose one of them on the first screen. After selecting a room, you should subscribe to an appropriate _[room's topic](/JAVEO/clustered-chat/blob/master/app/actors/UserSocket.scala#L48)_. A [ChatRoom](/JAVEO/clustered-chat/blob/master/app/actors/ChatRoom.scala) actor is only to manage a cluster communication.

We invite you to create PR in order to cooperate with code.

**Comment by eduardofcgo** [comment]
@sergiuszkierat  Thanks for the quick reply and I will take your invitation.
It seems easy enough to implement what you suggest. The [UserSocket](https://github.com/JAVEO/clustered-chat/blob/master/app/actors/UserSocket.scala#L42) will take a specific room's id, which the actor will subscribe to.
A problem arises if I want to save state in a specific room. For that wouldn't I need a different actor for each one? In that case I'm having trouble getting my head around where to instantiate that actor. I guess I could create several in the controller, but what if I want to create them on demand when some user connects to a certain url?
Thanks a lot for you time.

**Comment by sergiuszkierat** [comment]
@eduardofcbg Not really, there should be only one UserSocket which is used to communicate between a user's browser and a web server. Instead of this, you should extend a [ChatMessage](https://github.com/JAVEO/clustered-chat/blob/master/app/actors/UserSocket.scala#L23). There should be changed a [chat.coffee](https://github.com/JAVEO/clustered-chat/blob/master/app/assets/javascripts/chat.coffee#L48) as well.

To have a state of your chat, you should use a persistance layer, so far a chat is volatile in his behaviour. If you switch between rooms, you should retrieve a data from server.

**Comment by eduardofcgo** [comment]
I was thinking of using akka's [event sourcing](http://doc.akka.io/docs/akka/snapshot/scala/persistence.html). Your suggestion simplifies a lot the problem, but in that case the actors will not have any actual state. I will rethink the solution.
Thanks a lot.

**Comment by eduardofcbg** [comment]
I also just realized that for example, with your suggestion I am unable to know which users are connected to a certain document. The only way would be to also persist this, which does not seem a great solution.

**Comment by sergiuszkierat** [comment]
Resolved by https://github.com/JAVEO/clustered-chat/pull/5
